package com.sharepark.data.remote.cloud

import android.content.Context
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

data class CloudUser(
    val uid: String,
    val displayName: String,
    val email: String?
)

sealed interface SignInResult {
    data class Success(val user: CloudUser) : SignInResult
    data object Cancelled : SignInResult
    data class Failure(val message: String) : SignInResult
}

/**
 * The signed-in account behind shared vehicles. Everything else in the app works without one —
 * an account is only needed to share a car or join someone else's.
 */
@Singleton
class AuthRepository @Inject constructor(
    @ApplicationContext private val context: Context
) {
    /**
     * False when the build has no Firebase project (no google-services.json). The shared-vehicle
     * UI hides itself in that case instead of offering buttons that can only fail.
     */
    val isAvailable: Boolean by lazy { FirebaseApp.getApps(context).isNotEmpty() }

    private val auth: FirebaseAuth get() = FirebaseAuth.getInstance()

    val currentUser: Flow<CloudUser?> =
        if (!isAvailable) {
            flowOf(null)
        } else {
            callbackFlow {
                val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser?.toCloudUser()) }
                auth.addAuthStateListener(listener)
                awaitClose { auth.removeAuthStateListener(listener) }
            }.distinctUntilChanged()
        }

    fun currentUserNow(): CloudUser? =
        if (isAvailable) auth.currentUser?.toCloudUser() else null

    /**
     * Shows Google's account picker and signs into Firebase with the chosen account.
     * [activityContext] must be an Activity — Credential Manager draws its sheet over it.
     */
    suspend fun signInWithGoogle(activityContext: Context): SignInResult {
        if (!isAvailable) return SignInResult.Failure("שיתוף רכבים לא הוגדר בגרסה הזו")
        val webClientId = webClientId()
            ?: return SignInResult.Failure("חסר מזהה OAuth של Google בהגדרות Firebase")

        return try {
            val request = GetCredentialRequest.Builder()
                .addCredentialOption(GetSignInWithGoogleOption.Builder(webClientId).build())
                .build()
            val credential = CredentialManager.create(activityContext)
                .getCredential(activityContext, request)
                .credential

            if (credential !is CustomCredential ||
                credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                return SignInResult.Failure("סוג התחברות לא נתמך")
            }
            val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
            val user = auth.signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
                .await()
                .user
                ?: return SignInResult.Failure("ההתחברות נכשלה")
            SignInResult.Success(user.toCloudUser())
        } catch (e: GetCredentialCancellationException) {
            SignInResult.Cancelled
        } catch (e: Exception) {
            Log.w(TAG, "Google sign-in failed", e)
            SignInResult.Failure("ההתחברות נכשלה: ${e.localizedMessage ?: e.javaClass.simpleName}")
        }
    }

    suspend fun signOut() {
        if (!isAvailable) return
        auth.signOut()
        // Otherwise the next sign-in silently reuses the same Google account.
        try {
            CredentialManager.create(context).clearCredentialState(ClearCredentialStateRequest())
        } catch (e: Exception) {
            Log.w(TAG, "Could not clear credential state", e)
        }
    }

    // Generated by the google-services plugin from google-services.json, so it can't be
    // referenced as R.string.default_web_client_id in a build that has no Firebase config.
    private fun webClientId(): String? {
        val id = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (id != 0) context.getString(id) else null
    }

    private fun FirebaseUser.toCloudUser() = CloudUser(
        uid = uid,
        displayName = displayName?.takeIf { it.isNotBlank() } ?: email?.substringBefore('@') ?: "משתמש",
        email = email
    )

    private companion object {
        const val TAG = "AuthRepository"
    }
}
